apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 3  # Number of PostgreSQL replicas
  storage:
    size: 20Gi  # Adjust based on your needs
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user
  enableSuperuserAccess: true
