apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  #imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0  # Use the custom image
  imageName: ghcr.io/immich-app/postgres:16-vectorchord0.4.2-pgvectors0.3.0
  instances: 2  # Number of PostgreSQL replicas
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg/immich-db/"
      endpointURL: "http://192.168.210.30:30188"
      s3Credentials:
        accessKeyId:
          name: garage-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: garage-s3-creds
          key: ACCESS_SECRET_KEY
        region:
          name: garage-s3-creds
          key: AWS_REGION
  enableSuperuserAccess: true
  postgresUID: 999
  postgresGID: 999
  managed:
    roles:
      - name: immich
        superuser: true
        login: true

      - name: app
        superuser: true
        login: true

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 15Gi
      storageClassName: longhorn
  monitoring:
    enablePodMonitor: false
  primaryUpdateStrategy: unsupervised
  postgresql:
    shared_preload_libraries:
      - 'vectors.so'
      - 'vchord'

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-daily-backup
  namespace: immich
spec:
  schedule: "0 0 2 * * *" # Daily at 2:00 AM
  cluster:
    name: immich-db