apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  #imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0  # Use the custom image
  imageName: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
  instances: 2  # Number of PostgreSQL replicas
  enablePDB: false
  enableSuperuserAccess: true
  managed:
    roles:
      - name: immich
        superuser: true
        login: true

      - name: app
        superuser: true
        login: true

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 15Gi
      storageClassName: longhorn
  monitoring:
    enablePodMonitor: false
  primaryUpdateStrategy: unsupervised
  # postgresql:
  #   shared_preload_libraries:
  #     - 'vectors.so'

#bootstrap:
# initdb:
#   database: immich
#   owner: immich
#   secret:
#     name: immich-pg-user
#    dataChecksums: true
#    postInitApplicationSQL:
#      - ALTER SYSTEM SET search_path TO "$user", public, vectors;
#      - SET search_path TO "$user", public, vectors;
#      - CREATE EXTENSION IF NOT EXISTS "vectors";
#      - CREATE EXTENSION IF NOT EXISTS "cube";
#      - CREATE EXTENSION IF NOT EXISTS "earthdistance";
#      - ALTER SCHEMA vectors OWNER TO "immich";
#      - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich";
#      - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
