apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-shared-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/local-storage/Homes/samuel
    server: 192.168.210.30
