apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/local-storage/Homes/samuel/immich
    server: 192.168.210.30
