apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-shared-pvc
spec:
  volumeName: immich-nfs-shared-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
